### ISSUE TITLE
Text files use an incorrect url

### ISSUE THREAD

**Issue by ponchojohn1234** [Xerbo/furaffinity-dl#29]
text documents don't support the new URL
https://d.facdn.net/download/art/user/stories/id/id.file.ext
they use the old style URL
https://d.facdn.net/art/user/stories/id/id.file.ext
here's an example:
https://www.furaffinity.net/view/34436711/
using the download button we get a text file, using the download submission button we get an "igame not found" error

**Comment by Kattus** [comment]
Since this is an upstream issue, you should blame furaffinity for it, it's much better they fix it rather than making a workaround.

I've opened a ticket for this and hopefully it'll be fixed soon.
![2020-01-02_14-44-41](https://user-images.githubusercontent.com/6226312/71669878-79b85f00-2d6e-11ea-8c4c-8ac2af265e40.png)

**Comment by Xerbo** [comment]
This appears to be fixed, closing.
